# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "altoros/gradle"
version = "0.0.1"
name = "Sample Gradle Buildpack"
homepage = "https://github.com/Altoros/cn-buildpacks-example/tree/master/cnb-components/buildpacks/gradle"

# Eligible stacks
[[stacks]]
id = "com.altoros.demo.cnb.stacks.ubuntu"

# Metadata about the buildpack
[[metadata.dependencies]]
id      = "jdk"
name    = "AdoptOpenJDK"
version = "1.11.0_11"
uri     = "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9_openj9-0.26.0/OpenJDK11U-jdk_x64_linux_openj9_11.0.11_9_openj9-0.26.0.tar.gz"
stacks  = [ "com.altoros.demo.cnb.stacks.ubuntu" ]