name: "Dev-owned buildpack example: github CICD build and publish to dockerhub from source"

on:
  push:
    branches:
      - dev-owned

jobs:
  dev-owned:
    runs-on: ubuntu-latest
    name: build and publish image
    steps:
      - uses: actions/checkout@v2
      - uses: buildpacks/github-actions/setup-pack@v4.1.0
      - name: test
        run: ./gradlew build test
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: package
        run: "pack build altorosdev/cn-buildpacks-example --builder paketobuildpacks/builder:base --publish"
