name: "Ops-owned buildpack example: github CICD build and publish to dockerhub from artifact"

on:
  watch:
    types: [started]

jobs:
  dev-owned:
    runs-on: ubuntu-latest
    name: build and publish image
    steps:
      - uses: actions/checkout@v2
      - uses: buildpacks/github-actions/setup-pack@v4.1.0
      - name: test
        run: ./gradlew build test
      - name: simulate publishing artifact to registry
        run: cp ./build/libs/*.jar ./artifacts/
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: directly publish final image
        run: "pack build altorosdev/cn-buildpacks-example --builder paketobuildpacks/builder:base --publish"

  ops-owned:
    runs-on: ubuntu-latest
    needs: 
      - dev-owned
    name: build and publish image
    steps:
      - uses: actions/checkout@v2
      - uses: buildpacks/github-actions/setup-pack@v4.1.0
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: package
        run: "pack build altorosdev/cn-buildpacks-example --path ./artifacts/spring-boot-0.0.1-SNAPSHOT.jar --builder paketobuildpacks/builder:base --publish"
