name: "Cloud native buildpack example: build and publish an application image"

on:
  watch:
    types: [started]

jobs:
  dev-owned:
    runs-on: ubuntu-latest
    name: dev-owned CI
    steps:
      - uses: actions/checkout@v2
      - uses: buildpacks/github-actions/setup-pack@v4.1.0
      - name: test
        run: ./gradlew test
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: directly publish final image
        run: "pack build altorosdev/cn-buildpacks-example --builder paketobuildpacks/builder:base --publish"

  ops-owned-dev-CI:
    runs-on: ubuntu-latest
    name: ops-owned dev CI
    steps:
      - uses: actions/checkout@v2
      - uses: buildpacks/github-actions/setup-pack@v4.1.0
      - name: test
        run: ./gradlew build test
      - uses: actions/upload-artifact@master
        name: simulate publishing artifact to registry
        with:
          name: app-jar
          path: ./build/libs/*.jar
  ops-owned-ops-CI:
    runs-on: ubuntu-latest
    needs: 
      - ops-owned-dev-CI
    name: ops-owned ops CI
    steps:
      - uses: buildpacks/github-actions/setup-pack@v4.1.0
      - uses: actions/download-artifact@master
        with:
          name: app-jar
          path: .
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build and publish app image
        run: "pack build altorosdev/cn-buildpacks-example --path ./*.jar --builder paketobuildpacks/builder:base --publish"
